### ISSUE TITLE
Updated action-gh-latest-repo version

### ISSUE THREAD

**Issue by varunsridharan** [surjithctly/gh-latest-repos#7]
Hi,

This project use the GitHub action [varunsridharan/action-gh-latest-repo](https://github.com/varunsridharan/action-gh-latest-repo) on the [master](https://github.com/varunsridharan/action-gh-latest-repo/tree/master) branch.

Due to changes into the branches management, the `master` branch is not longer supported and will be removed in 1 month
 _(EOL: 2020-11-28)_.

The current latest version is `1.0` from the [main](https://github.com/varunsridharan/action-github-workflow-sync/tree/main) branch.

```yaml
uses: varunsridharan/action-gh-latest-repo@1.0
```

OR

```yaml
uses: varunsridharan/action-gh-latest-repo@main
```

**Comment by surjithctly** [comment]
Where am I supposed to update this?

**Comment by varunsridharan** [comment]
@surjithctly 

Here : https://github.com/surjithctly/gh-latest-repos/blob/master/.github/workflows/gh-latest-repo.yml#L17
